# 1. EL NAMESPACE (Tu habitación aislada)
apiVersion: v1
kind: Namespace
metadata:
  name: mi-app-pro
---
# 2. EL DEPLOYMENT (Tus 2 instancias de Nginx)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-servidor-web
  namespace: mi-app-pro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-sitio
  template:
    metadata:
      labels:
        app: mi-sitio
    spec:
      containers:
      - name: nginx
        image: jclizano/mi-web:1164ea324b267c724e39222e3e7d3a02ace54775
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
# 3. EL SERVICE (La IP interna para el túnel)
apiVersion: v1
kind: Service
metadata:
  name: mi-servicio-web
  namespace: mi-app-pro
spec:
  selector:
    app: mi-sitio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  # Usamos ClusterIP porque solo entraremos vía port-forward
  type: ClusterIP 