name: CI de mi Aplicacion

on:
  push:
    branches: [ "main" ]

jobs:
  ejecutar-plantilla:
    # REEMPLAZA: 'tu-usuario/tu-repo' por el nombre real de tu repositorio
    uses: jclizano01/test01/.github/workflows/reusable-build.yml@main
    with:
      image_name: "jclizano/mi-web"
      version: "${{ github.sha }}"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}