name: CI de mi Aplicacion

on:
  push:
    branches: [ "main" ]

jobs:
  ejecutar-plantilla:
    # REEMPLAZA: 'tu-usuario/tu-repo' por el nombre real de tu repositorio
    uses: jclizano01/test01/.github/workflows/reusable-build.yml@main
    with:
      image_name: "jclizano/mi-web"
      version: "${{ github.sha }}"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  # NUEVO JOB PARA ARGO CD
  actualizar-despliegue:
    needs: ejecutar-plantilla # Solo corre si el build fue exitoso
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Actualizar imagen en el YAML
        run: |
          # Reemplaza 'deployment.yaml' por la ruta real de tu archivo de k8s
          # Este comando busca la imagen y le pone el nuevo hash del commit
          sed -i "s|image: jclizano/mi-web:.*|image: jclizano/mi-web:${{ github.sha }}|g" k8s/deployment.yaml

      - name: Commit y Push a GitHub
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add k8s/deployment.yaml
          git commit -m "chore: update image to ${{ github.sha }} [skip ci]"
          git push